branch-defaults:
  master:
    environment: Auditlog-env
global:
  application_name: AuditLog
  default_ec2_keyname: e-4yufutm3pd
  default_platform: Node.js
  default_region: ap-southeast-1
  sc: git